name: Build Android

on:
  push:
    branches: [ prod ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, x86_64-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build Android
        run: |
          cargo ndk -t arm64-v8a -t x86_64 -o artifacts/android build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: artifacts/android
